---
- name: Install bird
  become: True
  apt:
    name: bird
    state: present

- name: Configure bird
  template:
    src: bird.conf.j2
    dest: /etc/bird/bird.conf
    owner: bird
    group: bird
    mode: 0640
  notify: restart bird
