---
- name: Install bird
  become: True
  apt:
    name: bird
    state: present
  when: not bird_use_version_2

- name: Ensure bird is absent
  become: True
  apt:
    name: bird
    state: absent
  when: bird_use_version_2

- name: Install bird2
  become: True
  apt:
    name: bird2
    state: present
  when: bird_use_version_2

- name: Install rpki-client
  become: True
  apt:
    name: rpki-client
  when: bird_enable_rpki_client

- name: Configure bird
  become: True
  template:
    src: bird.conf.j2
    dest: /etc/bird/bird.conf
    owner: bird
    group: bird
    mode: 0640
  notify: restart bird

- name: Ensure rpki-client override directory exists
  become: True
  file:
    name: "/etc/systemd/system/rpki-client.service.d"
    state: directory
  when: bird_enable_rpki_client

- name: Configure rpki-client
  become: True
  template:
    src: rpki-service.override.conf.j2
    dest: /etc/systemd/system/rpki-client.service.d/override.conf
  notify: systemctl daemon-reload
  when: bird_enable_rpki_client
