---
- name: restart bird
  become: True
  systemd:
    name: bird
    state: restarted
    enabled: yes

- name: systemctl daemon-reload
  become: True
  systemd:
    daemon_reload: yes
    name: rpki-client
    state: started
